name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: "Importing results to Xray"
      uses: mikepenz/xray-action@v3.0.2
      with: 
        username: XrayCredentials.CLIENT_ID
        password: XrayCredentials.CLIENT_SECRET
        testFormat: "junit"
        testPaths: "testResult/test-result.xml"
        projectKey: "TES"
        testPlanKey: "TES-9"
        
